name: Android Master CI
On:
  Push:
    Branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # permit a workflow to get to the substance of the repository.
      - uses: actions/checkout@master
      # set up a JDK version to be Java 8.
      - name: setup JDK 1.8
      uses: actions/setup-java@master
      with:
        java-version: 1.8
      # build the Gradle, download the libraries which are required, 
      # index the project and make Gradle executable and the project runnable.
      - name: Make Gradle execuDockerfiletable
       run: git update-index --chmod=+x ./gradlew
      # assemble debug APK.
      - name: Build Debug APK
       run: ./gradlew assembleDebug
      # publish artifact
      - name: Releasing using Hub
       run: ./gradlew publishApk