name: Android Pull Request & Master CI

on:
  pull_request:
    branches:
      - 'master'
  push:
    branches:
      - 'master'

jobs:
  test:
    name: Run Unit Tests
    runs-on: ubuntu-18.04

    steps:
      - uses: actions/checkout@master
      - name: set up JDK 1.8
        uses: actions/setup-java@master
        with:
          java-version: 1.8
      - name: Unit tests
        run: bash ./gradlew test --stacktrace

  apk:
    name: Generate APK
    runs-on: ubuntu-18.04

    steps:
      - name: Extract branch name
        shell: bash
        run: echo "##[set-output name=branch;]$(echo ${GITHUB_REF#refs/heads/})"
        id: extract_branch
      - uses: actions/checkout@master
      - name: set up JDK 1.8
        uses: actions/setup-java@master
        with:
          java-version: 1.8
      - name: Build debug APK
        run: bash ./gradlew assembleDebug --stacktrace
      - name: Upload APK
        uses: actions/upload-artifact@master
        with:
          name: ${{ steps.extract_branch.outputs.branch }}.apk
          path: app/build/outputs/apk/debug/app-debug.apk
      - name: Post to Slack
        run: |
          curl -X POST -H 'Authorization: Bearer ${{ secrets.SLACK_TOKEN }}' \
          'https://slack.com/api/files.upload' \
          -F 'file=@app/build/outputs/apk/debug/app-debug.apk' \
          -F channels=android \
          -F initial_comment=This build is ready for testing \
          -F filename=${{ steps.extract_branch.outputs.branch }}.apk \
          -F title=Android Build: ${{ steps.extract_branch.outputs.branch }}
